---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  # pre_tasks:
  #   - name: "wait 600 seconds for target connection to become reachable/usable."
  #     ansible.builtin.pause:
  #       seconds: 600

  tasks:
  # - name: "wait 600 seconds for target connection to become reachable/usable."
  #   ansible.builtin.pause:
  #     seconds: 600

  - name: "install python for Ansible."
    raw: apt -y update && apt install -y python-minimal
    when: check_python.rc != 0

    # Your code here

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
    # Add more env vars here

  roles:
    # Your code here