- name: Copy backend dist files to remote server
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: Install Node Modules
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Build Node Service
  shell: |
  echo "Navigate to backend"
  cd /home/ubuntu/backend
  
  echo "Run npm build
  npm run build

  echo "Run pm2 start"
  pm2 start npm --name backend -- start" \
  pm2 ls

# - name: Start app with PM2
#   shell: |
#     cd /home/ubuntu/backend
#     pm2 start npm -- run 

#  - name: delete existing pm2 processes if running
#    command: "npm install \
#              pm2 stop default \
#              pm2 start npm -- start"
#    ignore_errors: True
  #  become: yes
  #  become_user: rw_user

