 - name: delete existing pm2 processes if running
   command: "npm install \
             pm2 stop default \
             pm2 start npm -- start"
   ignore_errors: True
  #  become: yes
  #  become_user: rw_user

